title: " Our Special Moments" # or any other title you prefer
description: This is a collection of our cherished memories.
url: "https://Hitahlula22.github.io"
baseurl: "/birthdayyababy" # Note: Uncomment this line if using a user or organization site

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor


