title: "My Awesome Site"
description: "This is a description of my awesome site."
url: "https://hitalhula22.github.io" # Your GitHub Pages URL
baseurl: "/birthdayyababy" # The subpath of your site

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
