title: My Awesome Site
description: This is a description of my awesome site.
url: "https://<Hitahlula22>.github.io/<birthdayyababy>"
#baseurl: "/<repository-name>" # NOTE: delete this line if using a user or organization site

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
